services:
  prometheus:
    network_mode: host
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    network_mode: host
    image: grafana/grafana